apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment 
  labels:
    app: web
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: maksonviini/k8s-fastapi-app
          args: []
          ports:
            - containerPort: 8080
          resources: {}
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: web-api-svc
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
