apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
        - name: web-deployment-container
          image: maksonviini/k8s-fastapi-app
          ports:
            - name: http
              containerPort: 80
              hostPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  selector:
    app: web-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
