name: Create a infra on Digital Ocean

on:
  pull_request:
    branches:
      - master
  push:

env:
  DO_TOKEN: ${{ secrets.DO_TOKEN }}

jobs:
  iac:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: "terraform"

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Execute checkout
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init


      # - name: Terraform Plan
      #   uses:
