
name: Continuos Integration

on: 
  pull_request:
    branches:
      - master
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v3

      - name: Instala o Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" 

      - name: Pacote pip
        uses: BSFishy/pip-action@v1
        with:    
          requirements: dev-requirements.txt
          no-deps: true
          pre: true
          editable: editable
          platform: ':all:'
          upgrade: true
          extra: extra options
      
      - name: Instala dependencias
        run: pip install -r dev-requiriments.txt
      
      - name: Executa o black
        run: black .