name: Continuos Integration/ Continuos Delivery

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Execute checkout
        uses: actions/checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Package pip and install dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: dev-requirements.txt
          no-deps: true
          upgrade: true

      - name: Execute black lint
        run: black .

  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Execute checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-fastapi-app:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-fastapi-app:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Execute checkout
        uses: actions/checkout@v3

      - name: Define Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          cluster-type: generic

      - name: Deploy to Kubernetes Cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-fastapi-app:v${{ github.run_number }}
          manifests: |
            k8s/Deployment.yml
          strategy: basic
          action: deploy
          token: ${{ github.token }}
